---
- name: Clone repository
  hosts: all
  become: true
  tasks:
    - name: Clone repository
      git:
        repo: https://github.com/iphilka/stud-template.git
        dest: /home/ansible-worker/www/
        update: yes
        clone: yes
      when: ansible_user == 'ansible-worker'
